services:
  - type: web
    name: edulink-backend
    env: node
    buildCommand: cd edulink-backend && npm install
    startCommand: cd edulink-backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        value: wss://edutech-do3yznbl.livekit.cloud
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
